require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  IgnoredMethods:
    - describe
    - context
    - shared_examples
    - it
    - Dir.mktmpdir
    - shared_context

Style/Documentation:
  Enabled: false

Style/SymbolProc:
  Enabled: false

RSpec/ExampleLength:
  Max: 40

Gemspec/RequireMFA:
  Enabled: false
